#!/bin/bash
## Elastic Stack Prerequisites Install

###################
## Set variables ##
###################
ELASTIC_IP=$(ip -o -4 addr list ens160 | awk '{print $4}' | cut -d/ -f1)
ELASTIC_VM_NAME=$HOSTNAME
ELASTIC_DNS_NAME=elk.metsilabs.local

# Function to check and remove locks
remove_locks() {
    echo Mets1Tech | sudo -S rm -f /var/lib/dpkg/lock-frontend
    sudo rm -f /var/lib/dpkg/lock
    sudo dpkg --configure -a
}


########################################
## Install and configure Elaticsearch ##
########################################

# Remove any existing locks
remove_locks

echo "INFO: Installing Elasticsearch"
# Install Elaticsearch
sudo apt-get install elasticsearch

echo "INFO: Updating elasticsearch.yml"
# Update elasticsearch.yml
sudo sed -i -e "s/#node.name: node-1/node.name: ${ELASTIC_VM_NAME}/g" /etc/elasticsearch/elasticsearch.yml
sudo sed -i -e "s/#network.host: 192.168.0.1/network.host: ${ELASTIC_IP}/g" /etc/elasticsearch/elasticsearch.yml
sudo sed -i -e 's/#http.port: 9200/http.port: 9200/g' /etc/elasticsearch/elasticsearch.yml
sudo sed -i -e "s/#cluster\.initial_master_nodes: \[\"node-1\", \"node-2\"\]/cluster.initial_master_nodes: \[\"${ELASTIC_VM_NAME}\"\]/g" /etc/elasticsearch/elasticsearch.yml

# enable Elastic security by adding the following 
sudo -- sh -c "echo xpack.security.enabled: true >> /etc/elasticsearch/elasticsearch.yml"

echo "INFO: Reloading server manager"
# Reload systemd service manager
sudo systemctl daemon-reload

echo "INFO: Starting Elasticsearch"
# Start elasticsearch service and add to system boot
sudo systemctl start elasticsearch
sudo systemctl enable elasticsearch 

echo "INFO: Creating passwords for Elasticsearch users"
# Generate password for the built-in users on Elasticsearch 
yes | sudo  /usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto -u "http://${ELASTIC_IP}:9200" > elastic_passwords.txt

echo "INFO: Saving password to file"
# Save password as variables
PASSWORD_ELASTIC=$(grep "PASSWORD elastic = " elastic_passwords.txt | awk -F'= ' '{print $2}')
PASSWORD_KIBANA_SYSTEM=$(grep "PASSWORD kibana_system = " elastic_passwords.txt | awk -F'= ' '{print $2}')
PASSWORD_KIBANA=$(grep "PASSWORD kibana = " elastic_passwords.txt | awk -F'= ' '{print $2}')

echo "INFO: PASSWORD_ELASTIC = $PASSWORD_ELASTIC"
echo "INFO: PASSWORD_KIBANA_SYSTEM = $PASSWORD_KIBANA_SYSTEM"
echo "INFO: PASSWORD_KIBANA = $PASSWORD_KIBANA"

echo "INFO: Testing Elasticsearch"
# Test Elasticsearch installation 
curl -X GET -u elastic:$PASSWORD_ELASTIC "http://${ELASTIC_IP}:9200/?pretty"